### ISSUE TITLE
Sugestia zwrócenia komponentu Image za pomocą funkcji

### ISSUE THREAD

**Issue by dkarski** [fryderykg/gallery-exercise-react#2]
https://github.com/fryderykg/gallery-exercise-react/blob/29c23bdd7a82d08223b9c0a2a691bfda111f1b78/src/components/Images/Images.js#L14

**Comment by dkarski** [comment]
spróbowałbym zwrócenie komponentu Image przenieść do osobnej funkcji, pozwoliłaby Ci ona jednocześnie użyć jej w 27 linijce, gdzie także spodziewasz się indetycznie takiego samego komponentu

**Comment by fryderykg** [comment]
Komponent Image jest teraz zwracany jako funkcja.
